config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  get 'sessions/create'

  get 'sessions/destroy'
  
  resources :users

  resources :projects
  
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  
  get 'projects/' => redirect('projects/index')
  
  # collaborators
  post 'projects/:id/request', to: 'projects#request_collab', as: :request_collab
  post 'projects/:id/approve', to: 'projects#approve', as: :approve
  post 'projects/:id/reject', to: 'projects#reject', as: :reject
  post 'projects/:id/delete_collaborator', to: 'projects#delete_collaborator', as: :delete_collaborator
  
  # tags
  get 'tags/:tag', to: 'projects#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'pages#home'
  get '/about' => 'pages#about'
  # root :to => redirect('pages/home')
  
  # authentication
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :chatroom_users
    has_many :users, through: :chatroom_users
    has_many :messages
    belongs_to :project
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    if current_user
      @chatrooms = Chatroom.all
    else
      flash[:notice] = "You must be signed in to view chatrooms."
      redirect_to '/'
    end
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
   if @chatroom.project.collaborators.where(id: current_user).any? 
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse.each
   else 
     flash[:notice] = "You do not have access to this chatroom."
     redirect_to chatrooms_path
   end
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom, local: true) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :chatroom_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
  <div class="project-header">
    <h2 class="project-heading text-uppercase">Chatrooms</h2>
    <h3 class="project-text">
      Each project you create comes with a chatroom.<br/>
      Chat with your collaborators and get started on your project.<br/>
      Ready, set, collab!<br/>
  </div>



    <div class="project-table-list-container">
    <div class="project-table-list">
        <table id="chatrooms">
          <thead>
            <tr>
              <th>Title</th>
              <th>Chatroom</th>
            </tr>
            </thead>
            <tbody>
            <% @chatrooms.each do |chatroom| %>
                <% if chatroom.project.collaborators.where(id: current_user).any? %>
                  <tr>
                    <td><%= chatroom.name %></td>
                    <td><%= link_to 'Chat', chatroom_path(chatroom) %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
        </table>
    </div>
      

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<div class="chatroom">
  <div class="row">
    <div class="col-sm-3 col-md-3 col-lg-3"> 
      <div class="sidenav">
              <h3><%= @chatroom.name %></h3>
              <%= link_to "Project page", project_path(@chatroom.project) %>
              <br>
              <div>Collaborators: <%= raw @chatroom.project.collaborators.map { |c| link_to c.name, user_path(c) }.join(' ') %></div>
            <hr>
            <div class ="otherchatrooms">
              Other Chatrooms
              <ul>
                <% current_user.chatrooms.each do |chatroom| %>
                <li>
                  <%= link_to chatroom.name, chatroom_path(chatroom) %>
                  </li>
                <% end %> 
              </ul>
            </div>
      </div>
    </div>
    <div class="col-sm- 9 col-md-9 col-lg-9">

      <div class="chatroom-style-div">
      <div data-behavior='messages' data-chatroom-id='<%= @chatroom.id %>'>
        <% @messages.each do |message| %>
          <%= render message %>
        <% end %>
      </div>
      <div>
      <%= form_for [@chatroom, Message.new] do |f| %>
        <%= f.text_area :body, rows: 1, class: "form-control", style: "position:sticky;", autofocus: true %>
      <% end %>
      </div>
    </div>
    </div>
  </div>
</div>