config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  get 'sessions/create'

  get 'sessions/destroy'
  
  resources :users

  resources :projects
  
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  
  get 'projects/' => redirect('projects/index')
  
  # collaborators
  post 'projects/:id/request', to: 'projects#request_collab', as: :request_collab
  post 'projects/:id/approve', to: 'projects#approve', as: :approve
  post 'projects/:id/reject', to: 'projects#reject', as: :reject
  post 'projects/:id/delete_collaborator', to: 'projects#delete_collaborator', as: :delete_collaborator
  
  # tags
  get 'tags/:tag', to: 'projects#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'pages#home'
  get '/about' => 'pages#about'
  # root :to => redirect('pages/home')
  
  # authentication
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :projectusers
    has_many :potential_projects, ->{where(projectusers: {collaborator: true})}, through: :projectusers, :class_name=> 'Project', :source => :project
    has_many :collab_projects, ->{ where(projectusers: {collaborator: true})}, through: :projectusers, :class_name=> 'Project', :source => :project
	has_many :chatroom_users
	has_many :chatrooms, through: :chatroom_users
	has_many :messages
	
	def self.find_or_create_from_auth_hash(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
          user.provider = auth.provider
          user.uid = auth.uid
          user.name = auth.info.first_name
          user.oauth_token = auth.credentials.token
          user.oauth_expires_at = Time.at(auth.credentials.expires_at)
          user.save!
		end
	end
	
	def created_projects
	    Project.where(id: Projectuser.select('project_id').where(user_id: self.id).where(creator:true))
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :store_return_to
  
  def edit
    user = User.find(params[:id])
    if current_user == user
      @user = user
    else
      flash[:notice] = "You are not authorized to edit this profile."
      redirect_to user_path(user)
    end 
  end
  
  def show
    id = params[:id]
    @user = User.find(id)
  end
  
  def update 
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "Your account was successfully updated!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.created_projects.each do |project|
      Projectuser.where(project_id: project.id).each do |p|
        p.destroy
      end
      Tagging.where(project_id: project.id).each do |t|
        t.destroy
      end
      ChatroomUser.where(chatroom_id: project.chatroom.id).each do |c|
        c.destroy
      end
      Message.where(chatroom_id: project.chatroom.id).each do |m|
        m.destroy
      end
      project.chatroom.destroy
      project.destroy
    end
    Projectuser.where(user_id: params[:id]).each do |p|
      p.destroy
    end
    ChatroomUser.where(user_id: user.id).each do |c|
      c.destroy
      end
    Message.where(user_id: user.id).each do |m|
      m.destroy
    end
    
    User.find(user.id).destroy
    flash[:notice] = "#{user.name} was deleted."
    redirect_to '/'
  end 
  
  private
  def user_params
    params.require(:user).permit(:interests, :skills, :bio)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- Header -->
<div class="account-header">
	<h2 class="account-heading text-uppercase">EDIT PROFILE</h2>
</div>


<div class="account-container">
	<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@user.errors.count, "error") %> prohibited this profile from being saved:</h2>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="profile-form">
		<div class="form-group">
			<%= f.label :interests %><br />
			<%= f.text_field :interests, class: 'form-control formFields' %>
		</div>
		<div class="form-group">
			<%= f.label :skills %><br />
			<%= f.text_field :skills, class: 'form-control formFields', maxlength: 50 %>
		</div>
		<div class="form-group">
			<%= f.label :bio, "Description" %><br />
			<%= f.text_area :bio, class: 'form-control formFields', rows: 5, maxlength: 500 %>
		</div>
		<center><%= f.submit "update profile", class: "account-table-btn btn-primary js-scroll-trigger"%></br></br>
			<% end %>
			<%= button_to "delete account", user_path(@user), :method => :delete, data: {confirm: "Are you sure you want to delete your account? All of your created projects will be gone forever. :'("}, class: "account-table-btn btn-primary js-scroll-trigger btn-caution" %>
		</center>
		</br>
	</div>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
	<div class="account-header">
		<h2 class="account-heading text-uppercase">ACCOUNT INFORMATION</h2>
	</div>
	
	
	<div class="account-container">
		<div class="tab" role="tabpanel">
			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active"><a href="#1" aria-controls="1" role="tab" data-toggle="tab">Profile</a></li>
				<li role="presentation"><a href="#2" aria-controls="2" role="tab" data-toggle="tab">Projects</a></li>
				<li role="presentation"><a href="#3" aria-controls="3" role="tab" data-toggle="tab">Collaborations</a></li>
			</ul>
			<div class="tab-content">
			  
			  
				<div role="tabpanel" class="tab-pane fade in active" id="1">
					<div class="account-bio">
						<div style= "float:right">
							<% if @user == current_user %>
							<%= button_to "edit profile", edit_user_path(@user), :method => :get, class: "account-table-btn btn-primary js-scroll-trigger"%>
							<% end %> 
						</div>
						<br>
						<br>
						<center>
							<img src="/images/alfie_logo1.png" class="user-imag" style="width:15%; border-radius: 50%;">
							<h1><%= @user.name %></h1>
							<div align="center" style="color:gray">Joined <%= @user.created_at.strftime("%m-%d-%Y") %></div>
							<br>
							<br>
						</center>
						<div align="left">
							<h4>Interests: <%= @user.interests %></h4>
						</div>
						<div align="left">
							<h4>Skills: <%= @user.skills %></h4>
						</div>
						<hr/>
						<h4>Bio: <%= simple_format @user.bio %></h4>
						<hr/>
					</div>
				</div>
				
				
				<div role="tabpanel" class="tab-pane fade in" id="2">
					<h2 class="column-title" style="text-align:center; margin-top: 2em ">PROJECTS CREATED</h2>
					<div class="project-list-info">
						<% if @user.created_projects.blank? == false %>
						<div class="project-table-list">
							<table id="projects">
								<thead>
									<tr>
										<th>Title</th>
										<th>Summary</th>
										<% if @user == current_user %>
										<th>Project and Collaborators</th>
										<th>Notifications</th>
										<% end %>
									</tr>
								</thead>
								<tbody>
									<% @user.created_projects.each do |p| %>
									<tr>
										<td>
											<%= link_to p.title, project_path(p)  %>
										</td>
										<td>
											<%= p.summary%>
										</td>
										<% if @user == current_user %>
										<td>
											<table>
												<tr>
													<td style= "font-size: 0.75em">
														<center><%= button_to "manage", edit_project_path(p), :method => :get, class: "account-table-btn btn-primary js-scroll-trigger" %></center>
													</td>
													<td style= "font-size: 0.75em">
														<center><%= button_to "delete", project_path(p), :method => :delete, data: {confirm: "Are you sure you want to delete this project?"}, class: "account-table-btn btn-primary js-scroll-trigger" %></center>
													</td>
												</tr>
											</table>
										</td>
										<td>
											<% if p.potentials.length != 0 %>
											You have potentials waiting
											<%else%>
											No potentials
											<%end%>
										</td>
										<% end %> <!-- end for @user == current_user %> -->
									</tr>
									<% end %> <!-- end for @user.created_projects.each -->
								</tbody>
							</table>
						</div>
						<% else %> <!-- else for @user.created_projects -->      
						<h3 style="text-align:center; color:gray"> You haven't created any projects. Go start one!</h3>
						<% end %>      
					</div>
				</div>
				
				
				<div role="tabpanel" class="tab-pane fade in" id="3">
					<h2 class="column-title" style="text-align:center; margin-top: 2em ">PROJECT COLLABORATIONS</h2>
					<% if @user.collab_projects.blank? == false %>
					<div class="project-table-list">
						<table id="projects">
							<thead>
								<tr>
									<th>Title</th>
									<th>Creator</th>
									<th>Summary</th>
									<% if current_user == @user%>
									<th>Manage</th>
									<%end%>
								</tr>
							</thead>
							<tbody>
								<% @user.collab_projects.each do |p| %>
								<tr>
									<td>
										<%= link_to p.title, project_path(p)  %>
									</td>
									<td>
										<% if current_user != nil %>
										<% if p.creator.id == current_user.id %>
										<%= p.creator.name %> (You)
										<% else %>
										<%= link_to p.creator.name, user_path(p.creator) %>
										<% end %>
										<% else %> 
										<%= link_to p.creator.name, user_path(p.creator) %>
										<% end %>
									</td>
									<td>
										<%= p.summary %>
									</td>
									<% if current_user != p.creator && current_user == @user %>
									<td style= "font-size: 0.85em">
										<center><%= button_to "retract collab",reject_path(p, :user => current_user), :method => :post, data: {confirm: "Are you sure you don't want to be a collaborator?"}, class: "account-table-btn btn-primary js-scroll-trigger" %></center>
									</td>
									<%elsif current_user == p.creator%>
									<td style= "font-size: 0.85em">
										<center><%= button_to "manage", edit_project_path(p), :method => :get, class: "account-table-btn btn-primary js-scroll-trigger" %></center>
									</td>
									<%end%> 
								</tr>
								<% end %>
							</tbody>
						</table>
						<% else %> 
						<h3 style="text-align:center; color:gray"> You haven't requested to work on any projects. Go find one! </h3>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</html>