config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  get 'sessions/create'

  get 'sessions/destroy'
  
  resources :users

  resources :projects
  
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  
  get 'projects/' => redirect('projects/index')
  
  # collaborators
  post 'projects/:id/request', to: 'projects#request_collab', as: :request_collab
  post 'projects/:id/approve', to: 'projects#approve', as: :approve
  post 'projects/:id/reject', to: 'projects#reject', as: :reject
  post 'projects/:id/delete_collaborator', to: 'projects#delete_collaborator', as: :delete_collaborator
  
  # tags
  get 'tags/:tag', to: 'projects#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'pages#home'
  get '/about' => 'pages#about'
  # root :to => redirect('pages/home')
  
  # authentication
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :taggings
    has_many :tags, through: :taggings
    has_many :projectusers
    has_many :users, through: :projectusers
    has_many :collaborators, -> {where(projectusers: {collaborator: true})}, :through => :projectusers, :class_name=> 'User', :source => :user
    has_many :potentials, -> {where(projectusers: {collaborator: false})}, :through => :projectusers, :class_name=> 'User', :source => :user
    has_one :chatroom
    
    validates :title, :presence => true
    validates :summary, :presence => true
    validates :description, :presence => true
    
    def self.tagged_with(name)
        Tag.find_by!(name: name).projects
    end
 
    def self.tag_counts
        Tag.select('tags.id, tags.name, count(taggings.tag_id) as count').joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
    end

    def tag_list
        tags.map(&:name).join(', ')
    end
    
    def tag_list=(names)
        self.tags = names.downcase.split(',').map do |n|
            Tag.where(name: n.strip).first_or_create!
        end
    end
    
    # creator methods
    def add_creator=(user)
        Projectuser.where(user_id: user).where(project_id: self.id).first_or_create!(:project_id => self.id, :user_id => user, :collaborator => true, :creator => true)
    end
    
    def creator
       User.find_by(id: Projectuser.select('user_id').where(project_id: self.id).where(creator: true));
    end
    
    # collaborator methods
    def collaborator_list
        collaborators.map(&:name).join(', ')
    end
    
    def add_collaborator=(user)
        Projectuser.where(user_id: user).where(project_id: self.id).first_or_create!(:project_id => self.id, :user_id => user, :collaborator => true, :creator => false)
    end
    
    
    # potential methods
    def add_potential=(user)
        Projectuser.where(user_id: user).where(project_id: self.id).first_or_create!(:project_id => self.id, :user_id => user, :collaborator => false, :creator => false)
    end
    
    def potential_list
       potentials.map(&:name).join(', ') 
    end
    
    def approve(user)
        Projectuser.where(user_id: user).update(collaborator: true)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :store_return_to
  skip_before_action :verify_authenticity_token

  def index
     @projects = if params[:tag]
      Project.tagged_with(params[:tag])
    else
      Project.all
    end
  end

  def new
    if current_user 
     @project = Project.new
    else
      flash[:notice] = "You must be signed in to create a new project."
      redirect_to projects_path
    end
  end
  
  def request_collab
    @project = Project.find(params[:id])
    @project.add_potential=(current_user.id)
    redirect_to project_path(@project)
  end
  
  def approve
    @project = Project.find(params[:id])
    user = User.find(params[:user])
    @project.approve(params[:user])
    @project.chatroom.chatroom_users.where(user_id: user.id).first_or_create
    flash[:notice] = "#{user.name} is now a collaborator."
    redirect_to edit_project_path(@project)
  end
  
  def reject
    @project = Project.find(params[:id])
    user = User.find(params[:user]).name
    Projectuser.where(project_id: params[:id]).find_by(user_id: params[:user]).destroy
    if User.find(params[:user]).name == current_user.name
      flash[:notice] = "You are no longer requesting to collab"
      redirect_to project_path(@project)
    else  
      flash[:notice] = "#{user} has been rejected."
      redirect_to edit_project_path(@project)
    end
  end
  
  def delete_collaborator
    @project = Project.find(params[:id])
    user = User.find(params[:user])
    @project.chatroom.chatroom_users.where(user_id: user.id).destroy_all
    Projectuser.where(project_id: params[:id]).find_by(user_id: params[:user]).destroy
    if user.id == current_user.id
      flash[:notice] = "You are no longer a collaborator on #{@project.title}."
      redirect_to project_path(@project)
    else  
      flash[:notice] = "#{user.name} is no longer a collaborator."
      redirect_to edit_project_path(@project)
    end
  end

  def show
    id = params[:id]
    @project = Project.find(id)
  end
  
  def create
    @project = Project.new(project_params)
    if @project.save
      @project.add_creator=(current_user.id)
      @project.tag_list=(project_params[:tag_list])
      flash[:notice] = "#{@project.title} was successfully created."
      @chatroom = Chatroom.new
      @chatroom.project = @project # making connection between project and chatroom
      @chatroom.name = @project.title
  
      respond_to do |format|
        if @chatroom.save
          @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
          format.html { redirect_to projects_path}
          format.json { render :show, status: :created, location: @chatroom }
        else
          format.html { render :new }
          format.json { render json: @chatroom.errors, status: :unprocessable_entity }
        end
      end
    else
      render :new
    end
  end
  
  def edit
    project = Project.find(params[:id])
    if current_user == project.creator
      @project = project
    else 
      flash[:notice] = "You are not authorized to edit this project."
      redirect_to project_path(project)
    end
  end
  
  def update 
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      @project.chatroom.update(:name => @project.title)
      flash[:notice] = "#{@project.title} was successfully updated."
      redirect_to project_path(@project)
    else
      render :edit
    end
  end
  
  def destroy
    Projectuser.where(project_id: params[:id]).each do |p|
      p.destroy
    end
    Tagging.where(project_id: params[:id]).each do |t|
      t.destroy
    end
    @project = Project.find(params[:id])
    ChatroomUser.where(chatroom_id: @project.chatroom.id).each do |c|
      c.destroy
    end
    Message.where(chatroom_id: @project.chatroom.id).each do |m|
      m.destroy
    end
    @project.chatroom.destroy
    @project.destroy
    flash[:notice] = "#{@project.title} was deleted."
    respond_to do |format|
      format.html { redirect_to user_path(current_user)}
      format.json { head :no_content }
    end

    # redirect_to user_path(current_user)
  end
  
  private
  def project_params
    params.require(:project).permit(:title, :summary, :description, :project_type, :tag_list)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<!-- Header -->

<div class="account-header">
  <h2 class="account-heading text-uppercase">Manage <%= @project.title %></h2>
</div>

<div class="account-container">
  
<div class="tab" role="tabpanel">
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#edit" aria-controls="1" role="tab" data-toggle="tab">Edit Projects</a></li>
		<li role="presentation"><a href="#potentials" aria-controls="2" role="tab" data-toggle="tab">Manage Potentials</a></li>
		<li role="presentation"><a href="#collaborators" aria-controls="3" role="tab" data-toggle="tab">Manage Collaborators</a></li>
	</ul>
	
	<div class="tab-content">
	  
		<div role="tabpanel" class="tab-pane fade in active" id="edit">
			<%= form_for @project do |f| %>
			<% if @project.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
				<ul>
					<% @project.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
			
			<h2 class="column-title" style="text-align:center; margin-top: 2em ">EDIT PROJECT</h2>
			
			<div class="new-project">
				<div class="form-group">
					<%= f.label :title %><br/>
					<%= f.text_field :title, class: 'form-control formFields' %>
				</div>
				<div class="form-group">
					<%= f.label :summary %><br/>
					<%= f.text_field :summary, class: 'form-control formFields', maxlength: 50 %>
				</div>
				<div class="form-group">
					<%= f.label :description, "Description" %><br/>
					<%= f.text_area :description, class: 'form-control formFields', rows: 5, maxlength: 500 %>
				</div>
				<div class="form-group">
					<%= f.label :project_type, "Project Type" %><br/>
					<%= f.select :project_type, ['Hobby', 'Academic', 'Startup'], {}, class: 'form-control formFields'%>
				</div>
				<div class="form-group">
					<%= f.label :tag_list, "Tags (separated by commas)" %><br/>
					<%= f.text_field :tag_list, class: 'form-control formFields' %>
				</div>
				<center>
				  <%= f.submit "update project", class: "account-btn btn-primary js-scroll-trigger"%>
				  <% end %>
				</center>
			</div>
			
		</div>
		
		
		<div role="tabpanel" class="tab-pane fade in" id="potentials">
			<div class="project-table-list">
				<table id="projects">
					<tbody>
						<% if @project.potentials.length == 0 %>
						<h3 style="text-align:center; color:gray">No potential collaborators</h3>
						<% end %>
						<% @project.potentials.each do |p| %>
						<tr>
							<td>
								<%= link_to p.name, user_path(p)  %>
							</td>
							<td>
								<%= button_to "Approve", approve_path(@project, :user => p), :method => :post, class: "account-btn btn-primary js-scroll-trigger" %>
							</td>
							<td>
								<%= button_to "Reject", reject_path(@project, :user => p), :method => :post, class: "account-btn btn-primary js-scroll-trigger" %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
		
		
		<div role="tabpanel" class="tab-pane fade in" id="collaborators">
			<div class="project-table-list">
				<table id="projects">
					<tbody>
						<% if @project.collaborators.length <= 1 %>
  						<h3 style="text-align:center; color:gray">You are the only collaborator. Go find some friends!</h3>
  						</br>
						<% end %>
						<% @project.collaborators.each do |c| %>
						<tr>
							<td>
								<%= link_to c.name, user_path(c)  %>
							</td>
							<td>
								<% if c == @project.creator %>
								Project creator
								<% else %>
								<%= button_to "Delete", delete_collaborator_path(@project, :user => c), :method => :post, class: "account-btn btn-primary js-scroll-trigger" %>
								<% end %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
		
		
	</div>
</div>
</div>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html>
  
  <div class="project-header">
    <h2 class="project-heading text-uppercase">Projects</h2>
    <h3 class="project-text">
      This is a list of projects users have created.<br/>
      Click on a user to see other projects they have created.<br/>
      Click on a project to see more information.<br/>
      Click on the 'New Project' to create your own.<br/>
    </h3>  
  </div>
  
  <div class="project-table-filter">
    <div style="width:100%; font-size: 1.3em">Click a tag to filter projects</div>
    
    <div id="tag_cloud">
      <% tag_cloud Project.tag_counts, %w[s m l] do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: css_class %>        
      <% end %>
    </div>
    
    <td>
      <% if current_user %>
      <a class="btn btn-primary js-scroll-trigger" href="/projects/new">New Project</a>
      <% else %>
        <div style="float:center; font-weight: bold; text-decoration: underline;"> <%= link_to "Login to create new project", '/auth/google_oauth2' %> </div>
      <% end %>
    </td>
      
  </div>
  
  
  <div class="project-table-list-container">
    <div class="project-table-list">
      <table id="projects">
        <thead>
          <tr>
            <th>Title</th>
            <th>Creator</th>
            <th>Summary</th>
          </tr>
          </thead>
          <tbody>
            <% @projects.each do |p| %>
              <tr>
                <td>
                  <%= link_to p.title, project_path(p)  %>
                </td>
                <td>
                  <%= link_to p.creator.name, user_path(p.creator) %>
                </td>
                <td>
                  <%= p.summary %>
                </td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>

</html>

app/views/projects/new.html.erb
<!DOCTYPE html>

<%= csrf_meta_tags %>
<html>
  
	<!--<% if @project.errors.any? %>-->
 <!-- 	<div id="error_explanation">-->
	<!--  	<h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>-->
 <!-- 		<ul>-->
	<!--  		<% @project.errors.full_messages.each do |msg| %>-->
	<!--    		<li><%= msg %></li>-->
	<!--  		<% end %>-->
 <!-- 		</ul>-->
 <!-- 	</div>-->
	<!--<% end %>-->
	
	<div class="account-header">
    <h2 class="account-heading text-uppercase">CREATE NEW PROJECT</h2>
  </div>

	
	<div class="new-project">
		<form accept-charset="UTF-8" action="/projects" method="post">
			<input name="utf8" type="hidden" value="&#x2713;">
			<input name="authenticity_token" type="hidden" value="x37DrAAwyIIb7s+w2+AdoCR8cAJIpQhIetKRrPgG5VA=">
			
			<div class="form-row centered">
				<div class="form-group">
					<label for="inputEmail4">Project Title*</label>
					<input type="text" class="form-control formFields" id="inputTitle" placeholder="The name of your awesome project!" name="project[title]" required>
				</div>
			</div>
			
			<div class="form-group">
				<label for="inputSummary">Summary*</label>
				<input type="text" class="form-control formFields" id="inputSummary" placeholder="Short summary of your project (max 50 characters)" maxlength="50" name="project[summary]" required>
			</div>
			
			<div class="form-group">
				<label for="inputDescription">Description*</label>
				<textarea class="form-control formFields" rows="5" placeholder="A longer description of your project (max 500 characters)" id="inputDescription" maxlength="500" name="project[description]" required></textarea>
			</div>
			
			<div class="form-row centered">
				<div class="form-group">
					<label for="inputProjectType">Project Type</label>
					<select id="inputProjectType" class="form-control formFields" name="project[project_type]">
						<option selected>Hobby</option>
						<option>Academic</option>
						<option>Startup</option>
					</select>
				</div>
				<div class="form-group">
					<label for="inputTags">Tags</label>
					<input type="text" class="form-control formFields" id="inputTags" placeholder="List of desired collaborator skills" name="project[tag_list]">
				</div>
			</div>
			
			<center>
			  <button type="submit" class="btn btn-primary js-scroll-triggery" name="commit" value="Create">Submit</button>
			</center>
		</form>
	</div>
</html>

app/views/projects/show.html.erb
<div class="account-header">
  <h2 class="account-heading text-uppercase"><%= @project.title %></h2>
</div>
  
<div class="project-info-container">
	  
		
		<div align="right">
			<% if current_user%>
			  <% if @project.creator == current_user %>
  	  		<%= button_to "Manage project", edit_project_path(@project), :method => :get, class: "account-btn btn-primary js-scroll-trigger" %>
	   		<%else%>
		    	<% if @project.collaborators.where(id: current_user).any?  %>
			      <%= button_to "Retract collab",delete_collaborator_path(@project, :user => current_user), :method => :post, data: {confirm: "Are you sure you don't want to be a collaborator?"}, class: "account-btn btn-primary js-scroll-trigger" %>
    			<% elsif @project.potentials.where(id: current_user).any?  %>
		      	<%= button_to "Retract request",reject_path(@project, :user => current_user), :method => :post, class: "account-btn btn-primary js-scroll-trigger" %>
	    		<% elsif @project.collaborators.where(id: current_user).empty? %>
      			<%= button_to "Request to collaborate", request_collab_path(@project), :method => :post, class: "account-btn btn-primary js-scroll-trigger" %>
    			<%end%>
	  		<%end%>
	  	<%else%>
	  		Sign in to collaborate
		  <%end%>
		</div>
		
		
		<div class="project-info" style="color:gray">Created <%= @project.created_at.strftime("%m-%d-%Y") %></div>
		<div class="project-info">Creator: <%= link_to @project.creator.name, user_path(@project.creator) %></div>
		<div class="project-info">Collaborators: <%= raw @project.collaborators.map { |c| link_to c.name, user_path(c) }.join(', ') %></div>
		<div class="project-info">Project Type: <%= @project.project_type %></div>
		<div class="project-info">Tags: <%= raw @project.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></div>
		</br>
		<hr/>
		</br>
		<center><%= simple_format @project.description %></center>
		</br>
		<hr/>
	</div>
	
	</br>
	</br>
	<div class="project-info-container">
		<div id="disqus_thread"></div>
		<script>
			/**
			*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
			*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
			/*
			var disqus_config = function () {
			this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
			this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
			};
			*/
			(function() { // DON'T EDIT BELOW THIS LINE
			var d = document, s = d.createElement('script');
			s.src = 'https://tech-studio.disqus.com/embed.js';
			s.setAttribute('data-timestamp', +new Date());
			(d.head || d.body).appendChild(s);
			})();
		</script>
		<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	</div>
</div>