config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  get 'sessions/create'

  get 'sessions/destroy'
  
  resources :users

  resources :projects
  
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  
  get 'projects/' => redirect('projects/index')
  
  # collaborators
  post 'projects/:id/request', to: 'projects#request_collab', as: :request_collab
  post 'projects/:id/approve', to: 'projects#approve', as: :approve
  post 'projects/:id/reject', to: 'projects#reject', as: :reject
  post 'projects/:id/delete_collaborator', to: 'projects#delete_collaborator', as: :delete_collaborator
  
  # tags
  get 'tags/:tag', to: 'projects#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'pages#home'
  get '/about' => 'pages#about'
  # root :to => redirect('pages/home')
  
  # authentication
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechStudio</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </head>

  <!-- NAVBAR -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class="navbar-brand">TechStudio</div>
      </div>
      
      <ul class="nav navbar-nav navbar-test">
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/projects">Projects</a></li>
        <% if current_user %>
          <li><a href="/chatrooms">Chat</a></li>
        <% end %>
      </ul>
      
      
        <ul class="nav navbar-nav navbar-test" style="float: right">
          <% if current_user %>
            <li><%= link_to "My Account", user_path(current_user) %></li>
            <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
          <% else %>
            <li><%= link_to"Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
          <% end %>
        </ul>
      
    </div>
  </nav>

<!-- BODY -->
  <body>
    <center>
    <div style="height:5em;" class="span12"></div>
    
    
      <% flash.each do |name, msg| %>
        <div class= "alert alert-info alert-dismissible fade in">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= content_tag :div, msg, id: "flash_#{name}" %>
        </div>
      <% end %>

    
    
    </center>
    <div>
      <%= yield %>
    </div>
  </body>
  
  
  

<div style="height:2em;" class="span12"></div>  
  
</html>